port = 5903
# port = 8443
https = false
cache_busting = true
backend_log_level = "warn" # "error" / "warn" / "info" / "debug" / "trace"

[redirect]
port = 8081
enabled = false

[watch]
frontend = [
    "frontend/Cargo.toml",
    "frontend/src",
    "frontend/field-derive/src",
]
backend = [
    "backend/Cargo.toml",
    "backend/src",
]
